export const SECTORS = [
  "Agriculture & Agroalimentaire",
  "Banque & Finance",
  "BTP & Immobilier",
  "Commerce & Distribution",
  "Énergie & Mines",
  "Industrie & Manufacture",
  "Numérique & Technologies",
  "Pétrole & Gaz",
  "Santé & Pharmacie",
  "Services & Conseil",
  "Télécommunications",
  "Tourisme & Hôtellerie",
  "Transport & Logistique",
  "Éducation & Formation",
  "Médias & Communication",
  "Autre",
];

export const COUNTRIES_CEEAC = [
  "Angola",
  "Burundi",
  "Cameroun",
  "Congo (Brazzaville)",
  "Gabon",
  "Guinée Équatoriale",
  "RCA (Centrafrique)",
  "RDC (Congo-Kinshasa)",
  "Rwanda",
  "São Tomé-et-Príncipe",
  "Tchad",
  "Autre pays africain",
  "Europe",
  "Amérique",
  "Asie",
  "Autre",
];
