CREATE TABLE `opportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('bid','ami','job') NOT NULL,
	`title` varchar(512) NOT NULL,
	`slug` varchar(512) NOT NULL,
	`organization` varchar(512) NOT NULL,
	`country` varchar(255) NOT NULL,
	`sector` varchar(255),
	`description` longtext,
	`budget` varchar(100),
	`currency` varchar(10) DEFAULT 'USD',
	`deadline` varchar(100),
	`amiType` varchar(100),
	`partners` varchar(512),
	`webinaire` varchar(512),
	`externalLink` varchar(1024),
	`contractType` varchar(100),
	`experienceLevel` varchar(100),
	`featured` boolean DEFAULT false,
	`status` enum('active','closed','draft') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `opportunities_id` PRIMARY KEY(`id`),
	CONSTRAINT `opportunities_slug_unique` UNIQUE(`slug`)
);
