INSERT IGNORE INTO `articleCategories` (`name`, `slug`) VALUES
('Politique', 'politique'),
('Économie', 'economie'),
('Business', 'business'),
('Investissements', 'investissements'),
('Société', 'societe'),
('Culture', 'culture'),
('Sport', 'sport'),
('Technologie', 'technologie'),
('Environnement', 'environnement'),
('Santé', 'sante'),
('Éducation', 'education'),
('Diplomatie', 'diplomatie'),
('Sécurité', 'securite'),
('Énergie', 'energie'),
('Agriculture', 'agriculture'),
('Mines & Ressources', 'mines-ressources'),
('Transport & Infrastructures', 'transport-infrastructures'),
('International', 'international'),
('Opinion', 'opinion'),
('Interview', 'interview');
